"""Fixed spatial failures; never include geometry, metadata or paths."""
from enum import StrEnum


class Code(StrEnum):
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    BUILDABLE_AREA_REQUIRED = "BUILDABLE_AREA_REQUIRED"
    UNSUPPORTED_BUILDABLE_AREA_GEOMETRY = "UNSUPPORTED_BUILDABLE_AREA_GEOMETRY"
    BUILDABLE_AREA_OUTSIDE_SITE = "BUILDABLE_AREA_OUTSIDE_SITE"
    BUILDABLE_AREA_STATUS_MISMATCH = "BUILDABLE_AREA_STATUS_MISMATCH"
    BUILDABLE_AREA_SITE_REFERENCE_MISMATCH = "BUILDABLE_AREA_SITE_REFERENCE_MISMATCH"
    BUILDABLE_AREA_PROJECT_REFERENCE_MISMATCH = "BUILDABLE_AREA_PROJECT_REFERENCE_MISMATCH"
    BUILDABLE_AREA_SCHEMA_INVALID = "BUILDABLE_AREA_SCHEMA_INVALID"
    NONCANONICAL_BUILDABLE_AREA = "NONCANONICAL_BUILDABLE_AREA"


class SpatialError(ValueError):
    def __init__(self, code: Code):
        self.code = Code(code)
        super().__init__(self.code.value)
