"""Fixed failures with no input diagnostics."""
from enum import StrEnum


class Code(StrEnum):
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    FLOOR_HEIGHT_REQUIRED = "FLOOR_HEIGHT_REQUIRED"
    INVALID_FLOOR_HEIGHT = "INVALID_FLOOR_HEIGHT"
    REQUIRED_CONSTRAINT_UNAVAILABLE = "REQUIRED_CONSTRAINT_UNAVAILABLE"
    INPUT_REFERENCE_MISMATCH = "INPUT_REFERENCE_MISMATCH"
    INPUT_GEOMETRY_MISMATCH = "INPUT_GEOMETRY_MISMATCH"
    UNSUPPORTED_MASSING_SITE_GEOMETRY = "UNSUPPORTED_MASSING_SITE_GEOMETRY"
    NO_MASSING_CAPACITY = "NO_MASSING_CAPACITY"
    NO_FEASIBLE_MASSING = "NO_FEASIBLE_MASSING"
    GEOMETRY_GENERATION_FAILED = "GEOMETRY_GENERATION_FAILED"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    NUMERIC_RANGE = "NUMERIC_RANGE"
    SCHEMA_UNAVAILABLE = "SCHEMA_UNAVAILABLE"
    OUTPUT_SCHEMA_INVALID = "OUTPUT_SCHEMA_INVALID"
    OUTPUT_EXISTS = "OUTPUT_EXISTS"
    IO_ERROR = "IO_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class MassingError(ValueError):
    def __init__(self, code: Code):
        self.code = Code(code)
        super().__init__(self.code.value)
