"""Fixed error codes: never attach input values or native diagnostics."""
from enum import StrEnum


class Code(StrEnum):
    INVALID_JSON = "INVALID_JSON"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"
    UNIT_REQUIRED = "UNIT_REQUIRED"
    UNSUPPORTED_UNIT = "UNSUPPORTED_UNIT"
    UNIT_CONFLICT = "UNIT_CONFLICT"
    CRS_REQUIRED = "CRS_REQUIRED"
    UNSUPPORTED_CRS = "UNSUPPORTED_CRS"
    UNSUPPORTED_TYPE = "UNSUPPORTED_TYPE"
    INVALID_METADATA = "INVALID_METADATA"
    INVALID_COORDINATES = "INVALID_COORDINATES"
    NONFINITE_COORDINATES = "NONFINITE_COORDINATES"
    NON_2D = "NON_2D"
    OPEN_BOUNDARY = "OPEN_BOUNDARY"
    TOO_FEW_VERTICES = "TOO_FEW_VERTICES"
    ZERO_AREA = "ZERO_AREA"
    INVALID_POLYGON = "INVALID_POLYGON"
    NUMERIC_RANGE = "NUMERIC_RANGE"
    INVALID_DXF = "INVALID_DXF"
    NO_BOUNDARY = "NO_BOUNDARY"
    AMBIGUOUS_BOUNDARY = "AMBIGUOUS_BOUNDARY"
    UNSUPPORTED_CURVE = "UNSUPPORTED_CURVE"
    UNSUPPORTED_WIDTH = "UNSUPPORTED_WIDTH"
    UNSUPPORTED_PLANE = "UNSUPPORTED_PLANE"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    IO_ERROR = "IO_ERROR"
    OUTPUT_EXISTS = "OUTPUT_EXISTS"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class GeometryError(ValueError):
    def __init__(self, code: Code):
        self.code = Code(code)
        super().__init__(self.code.value)
